### ISSUE TITLE
Comic book support (CBZ, CBR)

### ISSUE THREAD

**Issue by mcandre** [geometer/FBReader#228]
Please add support for comic books. They're just zip'ed or rar'ed bitmaps.

**Comment by darioshanghai** [comment]
+1

**Comment by geometer** [comment]
It now implemented in FBReader for Android

**Comment by mcandre** [comment]
+1 for dedication

**Comment by goodevilgenius** [comment]
I have a couple questions.

0. Where should feature requests/bugs be submitted for the Android plugin? On the FBReaderJ repo? There doesn't appear to be a separate repo for the plugin.
0. Is it not going to implemented in desktop FBReader? (since this issue was closed)
