### ISSUE TITLE
Can't login to Book Network in Cyanogenmod w/o Google Services

### ISSUE THREAD

**Issue by nathanairplane** [geometer/FBReader#282]
From the Illustrated Guide, it appears that it should be possible to access the Book Network even without Google Services. My phone with Google Services can access it just fine. But on my tablet with Cyanogenmod 12 and no Google Services (or any Google software) at all, when I try to log in through FBReader, after entering my username and password, all I get is a blank browser screen with the following address up top: https://books.fbreader.org/static/empty.html#

Any idea what could be wrong here?

**Comment by geometer** [comment]
This is correct URL, it means you logged in successfully and should be redirected back to FBReader. I guess you use old version of FBReader that has this issue. You can upload latest one from https://fbreader.org/FBReaderJ/

**Comment by nathanairplane** [comment]
Ah yes—I'm relying on F-Droid, and it only has up to 2.1-ics. Any idea why?

**Comment by geometer** [comment]
Just install version from https://fbreader.org/FBReaderJ. This is known issue, and I've commented on FDroid what they have to fix — no changes last half year.

**Comment by nathanairplane** [comment]
Thanks. I don't know why this is happening, but when I try to install the new version from the ice-cream-sandwich.apk, the result is simply "App not installed." This is on CyanogenMod 12.1/ Android 5.1.1

**Comment by geometer** [comment]
You cannot install official version if fdroid version is installed as they use other certificate. Just remove fdroid version before installing the official one. And yes, I think you have remove the launcher icon from the home screen and then add it back.

**Comment by geometer** [comment]
Btw, in this thread there is the commit f-droid has to apply to fix this https://github.com/geometer/FBReaderJ/issues/334
This is one-line change, fixed 5th May 2015
