### ISSUE TITLE
Hierarchical TOC

### ISSUE THREAD

**Issue by trentbradley** [geometer/FBReader#303]
Fbreader premium wont display TOC when its hierarchical

**Comment by trentbradley** [comment]
Here's the tox.ncx file in the epub giving me issues.
[toc.ncx.txt](https://github.com/geometer/FBReader/files/1677792/toc.ncx.txt)

**Comment by geometer** [comment]
In the latest FBReader? (2.8.8?) Could you please send the ePub (here, or to geometer@fbreader.org).

**Comment by trentbradley** [comment]
From your reponse email:
It is not a valid XML file. Just replace “Logistics & Supply Chain Management” with “Logistics &amp; Supply Chain Management”

**Comment by geometer** [comment]
"&" with "&amp;amp;" ;)
