### ISSUE TITLE
Font style size not recognized

### ISSUE THREAD

**Issue by AlfredoCubitos** [geometer/FBReader#312]
Hi,
on Linux changing the font size for standard paragraph has no effect.
Changing font type works fine.
Changing the the font size for all other text sections works as well.

Please fix that bug, because some books became unreadable because the font size is set to smallest size available.

**Comment by ildar** [comment]
Unclear: where you're changing the font size and how? What type of book?
May be screenshots could be useful...

**Comment by AlfredoCubitos** [comment]
I change the font size in: _Look and Feel Preferences_ -> _Style_ 

1) this text section has font style _Basic_ which is used for code. I can change this font size
2) this text section is _Standard Paragraph_ used for the reading content. I cannot change this font size. But I can change the font type (e.g. from arial to courier)

As you can see, different formatted text in between an standard paragraph can also be changed.

Btw: changing the system language has no effect to the Preference Menu  Widgets :-( only to the drop down menu

![fbreader](https://user-images.githubusercontent.com/13254396/69481919-d2164b80-0e15-11ea-9f8f-1eda90636ddf.png)

**Comment by ildar** [comment]
> What type of book?

Or if possible the book itself?

**Comment by AlfredoCubitos** [comment]
its  epub format.
The book is copyright protected, so I can not send the book.
But the error occurs  on several different epub books.
I can provide style sheet information.

Example format which is not recognized:
`<h2 class="title"><a id="ch13lvl2sec560"></a>How it works...</h2>`
Text in a simple `<p>` tag or without any tag

What is recognized:
Text in a code tag
`<code class="literal">compile()</code>`

The style information for the example image:

```
class="literal">platform</code> module. The local context is where new variables will be created:<pre class="programlisting">        globals = {'__builtins__':__builtins__, 
                   'Path': Path, 
                   'platform': platform} 
        locals = {} 
        exec(code, globals, locals) 
        return locals['Configuration'] 
</pre></li>
<li class="listitem">This returns only the defined <code class="literal">Configuration</code> class from the locals which are set by the executed module. Any other variables will be ignored.</li>
</ol>
</div>
</div>
<div class="section" title="How it works..."><div class="titlepage"><div><div><h2 class="title"><a id="ch13lvl2sec560"></a>How it works...</h2>
</div>
</div>
</div>
<p>The details of the Python language—syntax and semantics—are embodied in the <code class="literal">compile()</code> and <code class="literal">exec()</code> functions. The <code class="literal">exec()</code> function reflects the way Python handles global and local variables. There are two namespaces provided to this function. The global <code class="literal">namespace</code> instance includes <code class="literal">__builtins__</code> plus a class and module that might be used in the file.</p>
<p>The local variable namespace will have the new class created in it. This namespace has a <code class="literal">__dict__</code> attribute that makes it accessible via dictionary methods. Because of this, we can then extract the class by name. The function returns the class object for use throughout the application.</p>
<p>We can put any kind of object into the attributes of a class. Our example showed mapping objects. There's no limitation on what can be done when creating attributes at the class level.</p>
<p>We can have complex calculations within the <code class="literal">class</code> statement. We can use this to create attributes which are derived from other attributes. We can execute any kind of statement, including <code class="literal">if</code> statements and <code class="literal">for</code> statements to create attribute values.</p>
</div>
<div class="section" title="There's more..."><div class="titlepage"><div><div><h2 class="title"><a id="ch13lvl2sec561"></a>There's more...</h2>
```
When opening the book with _Sigil_ everything works fine ;-)

**Comment by ildar** [comment]
I guess the book has fixed font size in it. That's weird (for a e-book).
I'm not sure a reader _must_ handle that.
Anyways, this is why I prefer FB2 format: it's logical+structural vs.
visual (epub/html)
