### ISSUE TITLE
Book network suddenly stopped working on older android devices. [SOLUTION INCLUDED]

### ISSUE THREAD

**Issue by jmoraleda** [geometer/FBReader#320]
I understand this project is no longer open source, but I am writing the problem and solution in case it helps other users.

A few days ago I noticed that my older devices suddenly could not access my book network and gave the error "Failed to connect to host books.fbreader.org". This happened simultaneously to the fbreader app in several devices (but not in all).

The problem occurs with older devices that are no longer receiving OTA updates. The problem is that  the root certificate for books.fbreader.org expired ( https://thesslonline.com/blog/sectigo-addtrust-external-ca-root-expiring-may-30-2020)

Upgrading the root certificates contained in `/system/etc/security/cacerts` with the latest recommended certificates from `https://android.googlesource.com/platform/system/ca-certificates/+/master/files/` solved my problem. (Of course this requires a rooted phone).

**Comment by geometer** [comment]
Thanks. Does it make sense to update books.fbreader.org to use another certificate? Maybe Let's Encrypt one? I expect the problem will reappear in a few months or years, but maybe the time does matter.

**Comment by jmoraleda** [comment]
According to Sectigo's official notice on the topic, the new certificate root should be valid until until 2038.  https://support.sectigo.com/articles/Knowledge/Sectigo-AddTrust-External-CA-Root-Expiring-May-30-2020
